backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "News Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "announcements"
    label: "Announcements"
    folder: "content/announcements"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About Page"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "contact"
    label: "Contact Page"
    files:
      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "gallery"
    label: "Gallery Page"
    files:
      - file: "content/gallery.md"
        label: "Gallery"
        name: "gallery"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }